INSERT INTO  state  (name_state,status,country_id) values ('AMAZONAS','INACTIVE',3);
INSERT INTO  state  (name_state,status,country_id) values ('ANTIOQUIA','INACTIVE',3);
INSERT INTO  state  (name_state,status,country_id) values ('ARAUCA','INACTIVE',3);
INSERT INTO  state  (name_state,status,country_id) values ('ATLÁNTICO','INACTIVE',3);
INSERT INTO  state  (name_state,status,country_id) values ('BOLÍVAR','INACTIVE',3);
INSERT INTO  state  (name_state,status,country_id) values ('BOYACÁ','INACTIVE',3);
INSERT INTO  state  (name_state,status,country_id) values ('CALDAS','INACTIVE',3);
INSERT INTO  state  (name_state,status,country_id) values ('CAQUETÁ','INACTIVE',3);
INSERT INTO  state  (name_state,status,country_id) values ('CASANARE','INACTIVE',3);
INSERT INTO  state  (name_state,status,country_id) values ('CAUCA','INACTIVE',3);
INSERT INTO  state  (name_state,status,country_id) values ('CESAR','INACTIVE',3);
INSERT INTO  state  (name_state,status,country_id) values ('CHOCÓ','INACTIVE',3);
INSERT INTO  state  (name_state,status,country_id) values ('CÓRDOBA','INACTIVE',3);
INSERT INTO  state  (name_state,status,country_id) values ('CUNDINAMARCA','INACTIVE',3);
INSERT INTO  state  (name_state,status,country_id) values ('DISTRITO CAPITAL','INACTIVE',3);
INSERT INTO  state  (name_state,status,country_id) values ('GUAINÍA','INACTIVE',3);
INSERT INTO  state  (name_state,status,country_id) values ('GUAVIARE','INACTIVE',3);
INSERT INTO  state  (name_state,status,country_id) values ('LA GUAJIRA','INACTIVE',3);
INSERT INTO  state  (name_state,status,country_id) values ('MAGDALENA','INACTIVE',3);
INSERT INTO  state  (name_state,status,country_id) values ('META','INACTIVE',3);
INSERT INTO  state  (name_state,status,country_id) values ('NARIÑO','ACTIVE',3);
INSERT INTO  state  (name_state,status,country_id) values ('NORTE DE SANTANDER','INACTIVE',3);
INSERT INTO  state  (name_state,status,country_id) values ('PUTUMAYO','INACTIVE',3);
INSERT INTO  state  (name_state,status,country_id) values ('RISARALDA','INACTIVE',3);
INSERT INTO  state  (name_state,status,country_id) values ('SAN ANDRÉS Y PROVIDENCIA','INACTIVE',3);
INSERT INTO  state  (name_state,status,country_id) values ('SANTANDER','INACTIVE',3);
INSERT INTO  state  (name_state,status,country_id) values ('SUCRE','INACTIVE',3);
INSERT INTO  state  (name_state,status,country_id) values ('TOLIMA','INACTIVE',3);
INSERT INTO  state  (name_state,status,country_id) values ('VALLE','INACTIVE',3);
INSERT INTO  state  (name_state,status,country_id) values ('VAUPÉS','INACTIVE',3);
INSERT INTO  state  (name_state,status,country_id) values ('VICHADA','INACTIVE',3);

